/**
 * EPD Renewal Email Templates
 * Auto-populate with material details and supplier contact information
 */

export interface MaterialDetails {
  materialName: string;
  epdNumber?: string | null;
  manufacturer?: string | null;
  expiryDate: string;
  category?: string;
  unit?: string;
}

export interface ContactDetails {
  companyName: string;
  contactName?: string | null;
  email?: string | null;
  phone?: string | null;
}

export interface EmailTemplate {
  subject: string;
  body: string;
  to?: string;
}

/**
 * Generate renewal request email
 */
export function generateRenewalRequestEmail(
  material: MaterialDetails,
  contact: ContactDetails | null,
  projectName?: string,
  senderName?: string
): EmailTemplate {
  const formattedDate = new Date(material.expiryDate).toLocaleDateString('en-AU', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const subject = `EPD Renewal Request - ${material.materialName}${material.epdNumber ? ` (${material.epdNumber})` : ''}`;

  const greeting = contact?.contactName 
    ? `Dear ${contact.contactName},` 
    : `Dear ${contact?.companyName || 'EPD Team'},`;

  const body = `${greeting}

I am writing to request an updated Environmental Product Declaration (EPD) for the following material:

MATERIAL DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Material Name: ${material.materialName}
${material.epdNumber ? `EPD Number: ${material.epdNumber}` : ''}
${material.manufacturer ? `Manufacturer: ${material.manufacturer}` : ''}
${material.category ? `Category: ${material.category}` : ''}
Current EPD Expiry: ${formattedDate}
${projectName ? `\nProject: ${projectName}` : ''}

REQUEST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Could you please provide:
1. The latest version of the EPD for this product
2. Updated validity dates
3. Any changes to emission factors or environmental data

We require current EPD documentation to maintain compliance with Australian construction carbon reporting requirements and Green Star certification standards.

Please let me know if you need any additional information to process this request.

Thank you for your assistance.

Kind regards,
${senderName || '[Your Name]'}
${projectName ? `\nProject: ${projectName}` : ''}

---
This email was generated by CarbonConstruct - Australian Construction Carbon Calculator
`;

  return {
    subject,
    body,
    to: contact?.email || undefined,
  };
}

/**
 * Generate follow-up email for pending requests
 */
export function generateFollowUpEmail(
  material: MaterialDetails,
  contact: ContactDetails | null,
  originalRequestDate: string,
  senderName?: string
): EmailTemplate {
  const formattedRequestDate = new Date(originalRequestDate).toLocaleDateString('en-AU', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const subject = `Follow-up: EPD Renewal Request - ${material.materialName}${material.epdNumber ? ` (${material.epdNumber})` : ''}`;

  const greeting = contact?.contactName 
    ? `Dear ${contact.contactName},` 
    : `Dear ${contact?.companyName || 'EPD Team'},`;

  const body = `${greeting}

I am following up on my previous request dated ${formattedRequestDate} regarding the EPD renewal for:

Material: ${material.materialName}
${material.epdNumber ? `EPD Number: ${material.epdNumber}` : ''}
${material.manufacturer ? `Manufacturer: ${material.manufacturer}` : ''}

Could you please provide an update on the status of this request? We are working to a project deadline and require the updated EPD documentation for compliance reporting.

If you need any additional information, please let me know.

Thank you for your attention to this matter.

Kind regards,
${senderName || '[Your Name]'}

---
This email was generated by CarbonConstruct - Australian Construction Carbon Calculator
`;

  return {
    subject,
    body,
    to: contact?.email || undefined,
  };
}

/**
 * Generate thank you / confirmation email after receiving EPD
 */
export function generateThankYouEmail(
  material: MaterialDetails,
  contact: ContactDetails | null,
  newEpdNumber?: string,
  senderName?: string
): EmailTemplate {
  const subject = `Thank You - EPD Received for ${material.materialName}`;

  const greeting = contact?.contactName 
    ? `Dear ${contact.contactName},` 
    : `Dear ${contact?.companyName || 'EPD Team'},`;

  const body = `${greeting}

Thank you for providing the updated Environmental Product Declaration for:

Material: ${material.materialName}
${newEpdNumber ? `New EPD Number: ${newEpdNumber}` : material.epdNumber ? `EPD Number: ${material.epdNumber}` : ''}
${material.manufacturer ? `Manufacturer: ${material.manufacturer}` : ''}

We have updated our records and the new EPD has been incorporated into our project carbon calculations.

We appreciate your prompt response and look forward to continuing our work with ${contact?.companyName || 'your company'}.

Kind regards,
${senderName || '[Your Name]'}

---
This email was generated by CarbonConstruct - Australian Construction Carbon Calculator
`;

  return {
    subject,
    body,
    to: contact?.email || undefined,
  };
}

/**
 * Generate mailto link from email template
 */
export function generateMailtoLink(template: EmailTemplate): string {
  const params = new URLSearchParams();
  params.set('subject', template.subject);
  params.set('body', template.body);
  
  const mailtoUrl = template.to 
    ? `mailto:${template.to}?${params.toString()}`
    : `mailto:?${params.toString()}`;
  
  return mailtoUrl;
}

/**
 * Copy email template to clipboard
 */
export async function copyEmailToClipboard(template: EmailTemplate): Promise<boolean> {
  const fullText = `To: ${template.to || '[Recipient Email]'}
Subject: ${template.subject}

${template.body}`;

  try {
    await navigator.clipboard.writeText(fullText);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}
