import { useRef, useState } from 'react';
import html2pdf from 'html2pdf.js';
import { Button } from '@/components/ui/button';
import { FileDown, Loader2 } from 'lucide-react';
import { ReportData } from './ReportData';
import { ReportTemplate } from '@/pages/Reports';

export interface ReportBranding {
  companyName?: string;
  logoUrl?: string;
  contactEmail?: string;
  preparedBy?: string;
}

export interface PDFReportOptions {
  showWatermark?: boolean;
}

interface PDFReportProps {
  data: ReportData;
  template: ReportTemplate;
  branding?: ReportBranding;
  options?: PDFReportOptions;
}

const formatNumber = (num: number) => (num || 0).toFixed(2);

export function PDFReport({ data, template, branding, options }: PDFReportProps) {
  const reportRef = useRef<HTMLDivElement>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleDownload = async () => {
    if (!reportRef.current) return;
    
    setIsGenerating(true);
    try {
      const element = reportRef.current;
      const opt = {
        margin: 10,
        filename: `${data.project.name.replace(/\s+/g, '_')}_Carbon_Report.pdf`,
        image: { type: 'jpeg' as const, quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' as const }
      };
      
      await html2pdf().set(opt).from(element).save();
    } catch (error) {
      console.error('PDF generation failed:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const showWatermark = options?.showWatermark ?? false;

  return (
    <div className="space-y-4">
      <Button onClick={handleDownload} disabled={isGenerating} className="gap-2">
        {isGenerating ? (
          <>
            <Loader2 className="h-4 w-4 animate-spin" />
            Generating PDF...
          </>
        ) : (
          <>
            <FileDown className="h-4 w-4" />
            Download PDF Report
          </>
        )}
      </Button>

      {/* Hidden report content for PDF generation */}
      <div className="absolute left-[-9999px]">
        <div 
          ref={reportRef} 
          className="bg-white p-8 text-black"
          style={{ width: '210mm', minHeight: '297mm', fontFamily: 'Helvetica, Arial, sans-serif' }}
        >
          {/* Watermark */}
          {showWatermark && (
            <div 
              style={{
                position: 'absolute',
                top: '45%',
                left: '10%',
                right: '10%',
                transform: 'rotate(-35deg)',
                fontSize: '48px',
                color: '#e8e8e8',
                textAlign: 'center',
                opacity: 0.6,
                fontWeight: 'bold',
                zIndex: -1,
                pointerEvents: 'none',
              }}
            >
              SAMPLE REPORT
            </div>
          )}

          {/* Header */}
          <div className="border-b-2 border-[#2d5a27] pb-5 mb-8">
            <div className="flex justify-between items-start mb-2">
              <div>
                {branding?.companyName && (
                  <p className="text-sm font-bold text-gray-700 mb-1">{branding.companyName}</p>
                )}
                <h1 className="text-2xl font-bold text-[#2d5a27]">Carbon Assessment Report</h1>
                <p className="text-sm text-gray-500">{data.project.name}</p>
              </div>
              {branding?.logoUrl && (
                <img src={branding.logoUrl} alt="Logo" className="w-20 h-20 object-contain" />
              )}
            </div>
            <p className="text-xs text-gray-500">Generated: {new Date().toLocaleDateString()}</p>
            {branding?.preparedBy && (
              <p className="text-xs text-gray-500 mt-2">Prepared by: {branding.preparedBy}</p>
            )}
          </div>

          {/* Content based on template */}
          {template === 'executive' && <ExecutiveSummary data={data} />}
          {template === 'technical' && <TechnicalReport data={data} />}
          {template === 'compliance' && <ComplianceReport data={data} />}

          {/* Footer */}
          <div className="mt-8 pt-5 border-t border-gray-300 text-center text-xs text-gray-500">
            <p>Generated by CarbonConstruct - Australian Construction Carbon Calculator</p>
            {branding?.contactEmail && <p>Contact: {branding.contactEmail}</p>}
            
            {/* Disclaimer */}
            <div className="mt-4 pt-3 border-t border-gray-200 text-left">
              <p className="font-semibold text-gray-600 mb-1" style={{ fontSize: '7px' }}>DISCLAIMER</p>
              <p style={{ fontSize: '6px', lineHeight: 1.4, color: '#999' }}>
                This report is generated based on the data provided and standard emission factors from Australian government sources. 
                Results are estimates only and should not be used as the sole basis for regulatory compliance decisions. 
                CarbonConstruct provides this tool for informational purposes and does not guarantee accuracy of calculations. 
                Users should verify results with qualified environmental consultants for official reporting. 
                By using this service, you agree to our Terms of Service and Privacy Policy.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function ExecutiveSummary({ data }: { data: ReportData }) {
  return (
    <>
      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">Executive Summary</h2>
        <p className="text-sm text-gray-600 mb-4">
          Total emissions for {data.project.name}: {formatNumber(data.emissions.total)} tCO₂e
        </p>
        {data.project.description && (
          <p className="text-xs text-gray-500 mb-4">{data.project.description}</p>
        )}
      </section>

      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">Key Metrics</h2>
        <div className="flex gap-4 mb-4">
          <MetricBox label="Scope 1" value={`${formatNumber(data.emissions.scope1)} tCO₂e`} />
          <MetricBox label="Scope 2" value={`${formatNumber(data.emissions.scope2)} tCO₂e`} />
          <MetricBox label="Scope 3" value={`${formatNumber(data.emissions.scope3)} tCO₂e`} />
        </div>
      </section>

      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">Compliance Overview</h2>
        <ComplianceItem label="NCC Compliance" status={data.compliance.nccCompliant} />
        <ComplianceItem label="Green Star Eligible" status={data.compliance.greenStarEligible} />
        <ComplianceItem label="NABERS Ready" status={data.compliance.nabersReady} />
      </section>
    </>
  );
}

function TechnicalReport({ data }: { data: ReportData }) {
  return (
    <>
      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">Project Information</h2>
        <InfoRow label="Project Name" value={data.project.name} />
        <InfoRow label="Project Type" value={data.project.project_type} />
        {data.project.location && <InfoRow label="Location" value={data.project.location} />}
        {data.project.description && <InfoRow label="Description" value={data.project.description} />}
      </section>

      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">Executive Summary</h2>
        <div className="bg-[#f8fffe] border border-[#e0e7e0] rounded p-4 mb-4">
          <p className="text-sm font-bold text-[#2d5a27] mb-2">Total Carbon Emissions</p>
          <p className="text-xl font-bold text-[#1e3a1c]">{formatNumber(data.emissions.total)} tCO₂e</p>
        </div>
      </section>

      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">Emissions by Scope</h2>
        
        <EmissionCard 
          title="Scope 1: Direct Emissions (Fuel)" 
          value={formatNumber(data.emissions.scope1)}
          items={data.breakdown.fuelInputs?.map(f => ({
            name: f.fuelType || 'Unknown',
            emissions: formatNumber(f.totalEmissions),
            detail: `${f.quantity || 0} ${f.unit || 'L'}`
          })) || []}
        />

        <EmissionCard 
          title="Scope 2: Energy Indirect (Electricity)" 
          value={formatNumber(data.emissions.scope2)}
          items={data.breakdown.electricityInputs?.map(e => ({
            name: e.state || 'Unknown',
            emissions: formatNumber(e.totalEmissions),
            detail: `${e.quantity || 0} ${e.unit || 'kWh'}`
          })) || []}
        />

        <EmissionCard 
          title="Scope 3: Materials (Embodied Carbon)" 
          value={formatNumber(data.breakdown.materials?.reduce((sum, m) => sum + (m.totalEmissions || 0), 0) || 0)}
          items={data.breakdown.materials?.map(m => ({
            name: `${m.name || 'Unknown'} (${m.category || 'N/A'})`,
            emissions: formatNumber(m.totalEmissions),
            detail: `${m.quantity || 0} ${m.unit || 'kg'}`
          })) || []}
        />

        <EmissionCard 
          title="Scope 3: Transport" 
          value={formatNumber(data.breakdown.transportInputs?.reduce((sum, t) => sum + (t.totalEmissions || 0), 0) || 0)}
          items={data.breakdown.transportInputs?.map(t => ({
            name: t.mode || 'Unknown',
            emissions: formatNumber(t.totalEmissions),
            detail: `${t.distance || 0} km, ${t.weight || 0} kg`
          })) || []}
        />
      </section>

      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">Compliance Status</h2>
        <ComplianceItem label="NCC Compliance" status={data.compliance.nccCompliant} />
        <ComplianceItem label="Green Star Eligible" status={data.compliance.greenStarEligible} />
        <ComplianceItem label="NABERS Ready" status={data.compliance.nabersReady} />
      </section>
    </>
  );
}

function ComplianceReport({ data }: { data: ReportData }) {
  return (
    <>
      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">Compliance Assessment</h2>
        <p className="text-sm text-gray-600 mb-4">
          Detailed compliance assessment for {data.project.name} against Australian standards
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">NCC Compliance (National Construction Code)</h2>
        <div className="bg-[#f0f8f0] p-4 rounded mb-4">
          <ComplianceItem label="Status" status={data.compliance.nccCompliant} large />
          <InfoRow label="Total Emissions" value={`${formatNumber(data.emissions.total)} tCO₂e`} />
          <InfoRow label="Scope 1 (Direct)" value={`${formatNumber(data.emissions.scope1)} tCO₂e`} />
          <InfoRow label="Scope 2 (Energy)" value={`${formatNumber(data.emissions.scope2)} tCO₂e`} />
          <InfoRow label="Scope 3 (Indirect)" value={`${formatNumber(data.emissions.scope3)} tCO₂e`} />
        </div>
      </section>

      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">GBCA Green Star Assessment</h2>
        <div className="bg-[#f0f8f0] p-4 rounded mb-4">
          <ComplianceItem label="Eligibility" status={data.compliance.greenStarEligible} large />
          <InfoRow label="Total Emissions" value={`${formatNumber(data.emissions.total)} tCO₂e`} />
          <p className="text-xs text-gray-600 mt-3">
            Green Star eligibility is based on comprehensive environmental performance including emissions intensity, 
            materials selection, and operational efficiency.
          </p>
        </div>
      </section>

      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">NABERS Energy Assessment</h2>
        <div className="bg-[#f0f8f0] p-4 rounded mb-4">
          <ComplianceItem label="Readiness" status={data.compliance.nabersReady} large />
          <InfoRow label="Scope 2 Emissions" value={`${formatNumber(data.emissions.scope2)} tCO₂e`} />
          <p className="text-xs text-gray-600 mt-3">
            NABERS Energy rating requires comprehensive operational energy data. Scope 2 emissions are the 
            primary indicator of energy performance.
          </p>
        </div>
      </section>

      <section className="mb-6">
        <h2 className="text-lg font-bold text-[#2d5a27] border-b border-gray-300 pb-1 mb-3">Emission Summary</h2>
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="bg-gray-100">
              <th className="border border-gray-300 p-2 text-left">Scope</th>
              <th className="border border-gray-300 p-2 text-right">Emissions (tCO₂e)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border border-gray-300 p-2">Scope 1 (Direct)</td>
              <td className="border border-gray-300 p-2 text-right">{formatNumber(data.emissions.scope1)}</td>
            </tr>
            <tr>
              <td className="border border-gray-300 p-2">Scope 2 (Energy)</td>
              <td className="border border-gray-300 p-2 text-right">{formatNumber(data.emissions.scope2)}</td>
            </tr>
            <tr>
              <td className="border border-gray-300 p-2">Scope 3 (Indirect)</td>
              <td className="border border-gray-300 p-2 text-right">{formatNumber(data.emissions.scope3)}</td>
            </tr>
            <tr className="bg-[#f8fffe] font-bold">
              <td className="border border-gray-300 p-2">Total</td>
              <td className="border border-gray-300 p-2 text-right">{formatNumber(data.emissions.total)}</td>
            </tr>
          </tbody>
        </table>
      </section>
    </>
  );
}

// Helper components
function MetricBox({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-[#f8fffe] border border-[#e0e7e0] rounded p-3 flex-1">
      <p className="text-xs text-gray-500 mb-1">{label}</p>
      <p className="text-base font-bold text-[#2d5a27]">{value}</p>
    </div>
  );
}

function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex mb-2">
      <span className="w-36 text-sm font-bold text-gray-700">{label}:</span>
      <span className="text-sm text-gray-600 flex-1">{value}</span>
    </div>
  );
}

function ComplianceItem({ label, status, large }: { label: string; status: boolean; large?: boolean }) {
  return (
    <div className="flex mb-2">
      <span className={`${large ? 'w-36' : 'w-40'} text-sm font-bold text-[#2d5a27]`}>{label}:</span>
      <span className={`text-sm font-bold ${status ? 'text-green-600' : 'text-amber-600'}`}>
        {status ? '✓ Compliant' : '⚠ Review Required'}
      </span>
    </div>
  );
}

function EmissionCard({ title, value, items }: { title: string; value: string; items: { name: string; emissions: string; detail: string }[] }) {
  return (
    <div className="bg-[#f8fffe] border border-[#e0e7e0] rounded p-4 mb-4">
      <p className="text-sm font-bold text-[#2d5a27] mb-2">{title}</p>
      <p className="text-lg font-bold text-[#1e3a1c] mb-2">{value} tCO₂e</p>
      {items.length > 0 ? (
        items.map((item, i) => (
          <div key={i} className="flex ml-3 mb-1">
            <span className="w-40 text-xs text-gray-600">{item.name}</span>
            <span className="text-xs font-bold text-gray-800">{item.emissions} tCO₂e ({item.detail})</span>
          </div>
        ))
      ) : (
        <p className="text-xs text-gray-500 ml-3">No data available</p>
      )}
    </div>
  );
}
